name: restedwf
version: 0.7.0
description: >-
  Rested Web Framework
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ansicolor: 1.0.2
  path: ^1.6.2
  jaguar_jwt: ^3.0.0
  nanoid: ^1.0.0
  yaml: 3.1.1
  postgres: 2.4.3
  rested_script:
    git:
      url: https://github.com/thomasberge/rested_script
      ref: dev
  string_tools:
    git:
      url: https://github.com/thomasberge/string_tools
      ref: dev
