name: restedwf
version: 0.5.0
description: >-
  Rested Web Framework
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  ansicolor: 1.0.2
  path: ^1.6.2
  jaguar_jwt: ^2.1.6
  encrypt: ^4.0.2
  nanoid: ^1.0.0
  mysql1: ^0.17.1
  rested_script:
    git:
      url: https://github.com/thomasberge/rested_script
      ref: dev
  string_tools:
    git:
      url: https://github.com/thomasberge/string_tools
      ref: dev